# Generated by Django 3.2.13 on 2022-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='en_title',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
